<html>
<title>home</title>
<body>
   ${home_attr}
<p><a href="pathvars_tests/pojo_tests/my_pojo/name1/age1">pathvars pojo1</a>                            </p>
<p><a href="pathvars_tests/pojo_tests/my_pojo2/name2/age2">pathvars pojo2</a>                           </p>
<p><a href="pathvars_tests/pojo_tests/my_bean/bean_value/test">pathvars pojo3</a>                       </p>
<p><a href="pathvars_tests/from_autowired_request_var/pathvar_value/test">pathvars from req variable</a></p>
<p><a href="sessionattrs/test1">global session attributes test1</a></p>
</body>
</html>
